**Wildan Hafidz Mauludin**

**2141720007**

**Tugas**

- Lakukan klasifikasi pada data MNIST dengan menggunakan model ANN
- Anda diperbolehkan melakukan eksplorasi terhadap,
    - Metode pra pengolahan
    - Pemilihan fitur
    - Arsitektur ANN
    - Fungsi Aktiviasi
- ANN diimplementasikan dengan menggunakan tensorflow.
- DIKERJAKAN SECARA BERKELOMPOK
- JELASKAN HASIL YANG ANDA DAPATKAN,
    - AKURASI
    - CONFUSION MATRIX
    - KONFIGURASI MODEL --> MULAI DARI PRA PENGOLAHAN SAMPAI ARSITEKTUR ANN

**Jawab**

*Import Library dan Persiapan Data*

In [6]:
import tensorflow as tf
from keras import layers, models
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt

# Unduh dataset MNIST dari scikit-learn
mnist = fetch_openml('mnist_784')

# Pisahkan data gambar dan label
images = mnist.data.astype('float32')
labels = mnist.target.astype('int')

# Langkah 1: Pra-pemrosesan
images /= 255.0  # Skalakan data

# Bagi data menjadi data pelatihan dan pengujian
train_images, test_images, train_labels, test_labels = train_test_split(
    images, labels, test_size=0.2, random_state=42)

# Langkah 2: Definisikan arsitektur model ANN
model = models.Sequential([
    layers.Reshape(target_shape=(28, 28, 1), input_shape=(784,)),
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    layers.MaxPooling2D((2, 2)),
    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation='softmax')
])

# Langkah 3: Kompilasi model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Langkah 4: Latih model
history = model.fit(train_images, train_labels,
                    epochs=10, validation_split=0.2)

# Langkah 5: Evaluasi model pada data pengujian
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f'Akurasi pada data pengujian: {test_acc:.2f}')

c:\Users\hubun\anaconda3\Lib\site-packages\sklearn\datasets\_openml.py:1002: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


Epoch 1/10
1400/1400 [==============================] - 25s 17ms/step - loss: 0.1859 - accuracy: 0.9443 - val_loss: 0.1029 - val_accuracy: 0.9699
Epoch 2/10
1400/1400 [==============================] - 23s 17ms/step - loss: 0.0588 - accuracy: 0.9822 - val_loss: 0.0553 - val_accuracy: 0.9821
Epoch 3/10
1400/1400 [==============================] - 23s 17ms/step - loss: 0.0371 - accuracy: 0.9885 - val_loss: 0.0515 - val_accuracy: 0.9834
Epoch 4/10
1400/1400 [==============================] - 23s 17ms/step - loss: 0.0246 - accuracy: 0.9917 - val_loss: 0.0579 - val_accuracy: 0.9825
Epoch 5/10
1400/1400 [==============================] - 23s 17ms/step - loss: 0.0179 - accuracy: 0.9938 - val_loss: 0.0521 - val_accuracy: 0.9863
Epoch 6/10
1400/1400 [==============================] - 23s 17ms/step - loss: 0.0130 - accuracy: 0.9959 - val_loss: 0.0680 - val_accuracy: 0.9827
Epoch 7/10
1400/1400 [==============================] - 23s 17ms/step - loss: 0.0107 - accuracy: 0.9964 - val_loss: 0.0594 -

In [7]:
# Evaluasi akurasi data pelatihan
train_loss, train_acc = model.evaluate(train_images, train_labels)
print(f'Akurasi pada data pelatihan: {train_acc:.2f}')

1750/1750 [==============================] - 10s 6ms/step - loss: 0.0185 - accuracy: 0.9950
Akurasi pada data pelatihan: 1.00


In [9]:
from sklearn.metrics import confusion_matrix

# Membuat prediksi pada data pengujian
predictions = model.predict(test_images)
predicted_labels = np.argmax(predictions, axis=1)

# Membuat matriks kebingungan
confusion = confusion_matrix(test_labels, predicted_labels)
print('Matriks Kebingungan:')
print(confusion)

438/438 [==============================] - 2s 5ms/step
Matriks Kebingungan:
[[1334    1    2    0    1    1    2    0    1    1]
 [   0 1584    4    0    1    0    1    3    5    2]
 [   0    1 1372    1    1    0    1    1    2    1]
 [   1    1   16 1380    0   18    0    3    7    7]
 [   0    0    1    0 1275    0    1    1    7   10]
 [   0    0    1    1    0 1260    3    0    7    1]
 [   5    0    1    0    1    6 1381    0    2    0]
 [   1    0   19    1    2    0    0 1475    0    5]
 [   3    1    4    1    0    3    4    2 1335    4]
 [   4    0    1    2    9    4    0    4    5 1391]]
